# Generated by Django 5.1.4 on 2024-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("pub_date", models.DateField()),
                ("email", models.CharField(default="", max_length=50)),
                ("phone", models.CharField(default="", max_length=50)),
                ("desc", models.CharField(default="", max_length=500)),
            ],
        ),
    ]
