# Generated by Django 5.1.4 on 2024-12-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="pub_date",
        ),
    ]
