# Generated by Django 5.1.4 on 2024-12-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_orders_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="items_json",
            new_name="itemsJson",
        ),
    ]
