# Generated by Django 5.1.4 on 2024-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_rename_items_json_orders_itemsjson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="id",
        ),
        migrations.AddField(
            model_name="orders",
            name="order_id",
            field=models.AutoField(default="", primary_key=True, serialize=False),
        ),
    ]
