# Generated by Django 5.1.4 on 2024-12-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_orders_id_orders_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
