# Generated by Django 5.1.4 on 2024-12-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_orders_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="itemsJson",
        ),
        migrations.AddField(
            model_name="orders",
            name="itemJson",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.AutoField(default="", primary_key=True, serialize=False),
        ),
    ]
