# Generated by Django 5.1.4 on 2024-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_orders_itemsjson_orders_itemjson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
