# Generated by Django 5.1.4 on 2024-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_orders_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="itemJson",
        ),
        migrations.AddField(
            model_name="orders",
            name="itemsJson",
            field=models.TextField(default=""),
        ),
    ]
